### PR TITLE
Add hw2 file with new homework.

### PR DESCRIPTION
**Pull request by polezhaevalera**
Second homework with functions and regular expressions

### CODE REVIEW

**Comment by rinnifox** [comment]
Hi Valeria!

Nice work, good that you've used error handling here 👍🏻

However, I guess in your code you've mixed up ENSEMBL and Uniprot parts, which causes errors in result parsing. You have regexp for ENSEMBL but then `print("Uni")` and calling uniprot functions. 

```
def uniprot_or_ensembl_parse(ids: list):
  if np.all([bool(re.match('ENS[A-Z]+[0-9]{11}', gene)) for gene in ids]):
    print("Uni")
    resp = get_uniprot(ids)
    output = uniprot_parse_response(resp)
  elif np.all([bool(re.match('[OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2}', gene)) for gene in ids]):
    print("Ens")
    resp = get_ensembl(ids)
    output = ensembl_parse_response(resp)
  else:
    raise TypeError('No matches')
  return output
```

Also, a comment about ENSEMBL regular expression. 
In your code, an ID like `ENSMUSGRANDOMTEXT00000041147` will be accepted, as you allow to have any amount of literals after `ENS....` Please, check this [link](https://www.ensembl.org/info/genome/stable_ids/prefixes.html) and try to modify your rule a little bit.

There are two main things to note:
- Feature prefix (1 or 2 symbols indicating the type of the sequence);
- Species (nothing for human and a three-letter code for other ones; let's not concentrate on rare mice cases like MGP_AKRJ_).

Using this, you should be able to create more precise expression to filter ENSEMBL codes.

Fix this please by the next lecture, ok?

**Comment by rinnifox** [comment]
And your test IDs like `MGP_129S1SvImJ_G0019185` do not make much sense according to the regular expression for ENSEMBL that you are currently using 🙃 it is a valid ID for a rare case but your expression does not take it into the account.

**Comment by rinnifox** [comment]
Now it's better! 
But I think it should be `ENS[A-Z]{1,5}` instead of `ENS[A-Z]{1,6}`, isn't it?

**Comment by polezhaevalera** [comment]
Actually, I did not find any prefixes longer than 4 (ex. ENSCSAV), therefore I wrote ENS[A-Z]{1,4}

**Comment by rinnifox** [comment]
Hmm, you're right! 

There indeed is such a case. But then the first solution was correct, as you have to account both for feature prefix (1-2 letters) and for species prefix (seems to be possible having 4 letters, not only 3). So you can change back to {1,6} and merge PR after that.

**Pull request merged**
